package flip

const (
	BankStatusOperational                  = "OPERATIONAL"
	BankStatusDisturbed                    = "DISTURBED"
	BankStatusHeavilyDisturbed             = "HEAVILY_DISTURBED"
	BankAccountInquiryStatusPending        = "PENDING"
	BankAccountInquiryStatusSuccess        = "SUCCESS"
	BankAccountInquiryStatusInvalid        = "INVALID_ACCOUNT_NUMBER"
	BankAccountInquiryStatusSuspected      = "SUSPECTED_ACCOUNT"
	BankAccountInquiryStatusBlacklisted    = "BLACK_LISTED"
	BankAccountInquiryStatusFailed         = "FAILED"
	BankAccountInquiryStatusClosed         = "CLOSED"
	DisbursementStatusPending              = "PENDING"
	DisbursementStatusCancelled            = "CANCELLED"
	DisbursementStatusDone                 = "DONE"
	DisbursementReasonInactive             = "INACTIVE_ACCOUNT"
	DisbursementReasonNotRegistered        = "NOT_REGISTERED_ACCOUNT"
	DisbursementReasonCantReceive          = "CANT_RECEIVE_TRANSFER"
	DisbursementReasonIntermittent         = "INTERMITTENT_DISTURBANCE_ON_BENEFICIARY_BANK"
	DisbursementReasonAccountNotVerified   = "BENEFICIARY_ACCOUNT_NOT_VERIFIED"
	DisbursementReasonInsufficientBalance  = "INSUFFICIENT_BALANCE"
	CreatedFromApi                         = "API"
	CreatedFromDashboard                   = "DASHBOARD"
	DirectionDomesticTransfer              = "DOMESTIC_TRANSFER"
	DirectionDomesticSpecialTransfer       = "DOMESTIC_SPECIAL_TRANSFER"
	DirectionForeignInboundSpecialTransfer = "FOREIGN_INBOUND_SPECIAL_TRANSFER"
	IdentityTypeNationalId                 = "nat_id"
	IdentityTypeDrivingLicense             = "drv_lic"
	IdentityTypePassport                   = "passport"
	IdentityTypeBankAccount                = "bank_acc"
	JobHousewife                           = "housewife"
	JobEnterpreneur                        = "entrepreneur"
	JobPrivateEmployee                     = "private_employee"
	JobGovernmentEmployee                  = "government_employee"
	JobFoundationBoard                     = "foundation_board"
	JobIndonesianMigrantWorker             = "indonesian_migrant_worker"
	JobOthers                              = "others"
	UrlGetBalance                          = "/v2/general/balance"
	UrlGetBankInfo                         = "/v2/general/banks"
	UrlGetIsMaintenance                    = "/v2/general/maintenance"
	UrlGetBankAccountInquiry               = "/v2/disbursement/bank-account-inquiry"
	UrlCreateDisbursement                  = "/v3/disbursement"
	UrlGetDisbursement                     = "/v3/get-disbursement"
)
